name: 自动部署   # 步骤名称

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install dependencies
        run: |
          go mod download 
          go mod tidy

      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json

      - name: Build
        run: go build -v

      - name: 发布到阿里云
          uses: easingthemes/ssh-deploy@v2.1.5
          env:
            #私钥
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            #SCp参数
            ARGS: "-rltgoDzvO --delete"
            #源目录
            SOURCE: "./Test-Actions"
            #服务器Ip:换成你的服务器iP
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            #用户
            REMOTE_USER: ${{ secrets.SSH_USERNAME }}
            #目标地址
            TARGET: "/home/xingdao/chaintest/"

      作者：Eric223
      链接：https://juejin.cn/post/7157193707693801508
      来源：稀土掘金
      著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

      #      - name: SSH 命令删除旧文件
      #        uses: appleboy/ssh-action@master
      #        with:
      #          # 这里配置对应仓库设置的变量，就可以避免服务器配置暴露
      #          host: ${{ secrets.SSH_HOST }}
      #          username: ${{ secrets.SSH_USERNAME }}
      #          key: ${{ secrets.DEPLOY_KEY }}
      #
      #          # 先用 SSH 命令删除旧文件
      #          script: |
      #          #            rm -rf /www/blog/*